//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace igarden.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Allergy
    {
        public string Scientific_Name { get; set; }
        public string Common_name { get; set; }
        public Nullable<int> Very_poisonous { get; set; }
        public Nullable<int> Poisonous { get; set; }
        public Nullable<int> Allergenic { get; set; }
        public Nullable<int> Irritant { get; set; }
        public Nullable<int> Invasive { get; set; }
        public string Plant_id { get; set; }
        public string Image_src { get; set; }
    }
}
