//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace igarden.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plant
    {
        public string Type { get; set; }
        public string Genus { get; set; }
        public string Tube_colour { get; set; }
        public string Botanical_name { get; set; }
        public string Common_name { get; set; }
        public Nullable<int> Rain { get; set; }
        public string ph { get; set; }
        public Nullable<double> min_height { get; set; }
        public Nullable<double> max_height { get; set; }
        public Nullable<double> min_width { get; set; }
        public Nullable<double> max_width { get; set; }
        public string Soil { get; set; }
        public string Flower_Season { get; set; }
        public string Flower_Colour { get; set; }
        public string Frost_level { get; set; }
        public string Scientific_Name { get; set; }
        public string Fire_resistant { get; set; }
        public string Plant_id { get; set; }
        public string Img_src { get; set; }
        public List<Plant_Location> Occurances { get; set; }

    }

    public class Plant_Location
    {
        public double Latitude { get; set; }
        public double Longitude { get; set; }
    }
}

